/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.11
 * Generated at: 2021-10-05 05:45:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import java.text.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("   \r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html>\r\n");
      out.write("        <head>\r\n");
      out.write("            <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("            <title>JSP Page</title>\r\n");
      out.write("            <link\r\n");
      out.write("                href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("                rel=\"stylesheet\"\r\n");
      out.write("                integrity=\"sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU\"\r\n");
      out.write("                crossorigin=\"anonymous\"\r\n");
      out.write("                />\r\n");
      out.write("            <script src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.min.js\"></script>\r\n");
      out.write("            <script\r\n");
      out.write("                src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("                integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\r\n");
      out.write("                crossorigin=\"anonymous\"\r\n");
      out.write("            ></script>\r\n");
      out.write("            <link\r\n");
      out.write("                rel=\"stylesheet\"\r\n");
      out.write("                href=\"font/font-awesome-4.7.0/css/font-awesome.min.css\"\r\n");
      out.write("                />\r\n");
      out.write("            <link\r\n");
      out.write("                rel=\"stylesheet\"\r\n");
      out.write("                href=\"font/font-awesome-4.7.0/css/font-awesome.css\"\r\n");
      out.write("                />\r\n");
      out.write("        </head>\r\n");
      out.write("        <body>\r\n");
      out.write("            <div ng-app=\"easyParking\" ng-controller=\"controladorRegistro\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <a class=\"navbar-brand\">\r\n");
      out.write("                            <img\r\n");
      out.write("                                src=\"img/logo.png\"\r\n");
      out.write("                                class=\"d-inline-block align-text-top\"\r\n");
      out.write("                                alt=\"\"\r\n");
      out.write("                                width=\"30\"\r\n");
      out.write("                                height=\"24\"\r\n");
      out.write("                                />\r\n");
      out.write("                            EasyParking\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <button\r\n");
      out.write("                            class=\"navbar-toggler\"\r\n");
      out.write("                            type=\"button\"\r\n");
      out.write("                            data-bs-toggle=\"collapse\"\r\n");
      out.write("                            data-bs-target=\"#navbarNav\"\r\n");
      out.write("                            aria-controls=\"navbarNav\"\r\n");
      out.write("                            aria-expanded=\"false\"\r\n");
      out.write("                            aria-label=\"Toggle navigation\"\r\n");
      out.write("                            >\r\n");
      out.write("                            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("                            <ul class=\"navbar-nav\">\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link active\" aria-current=\"page\" href=\"index.jsp\"\r\n");
      out.write("                                       >Inicio</a\r\n");
      out.write("                                    >\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"nav-item\">\r\n");
      out.write("                                    <a class=\"nav-link\" href=\"#\" ng-click=\"listarRegistros()\"\r\n");
      out.write("                                       >Lista Registros</a\r\n");
      out.write("                                    >\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row m-3\">\r\n");
      out.write("                        <div class=\"col-10\">\r\n");
      out.write("                            <h2>GESTIÓN DE PARQUEADERO</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-2 ps-5\">\r\n");
      out.write("                            <button\r\n");
      out.write("                                type=\"button\"\r\n");
      out.write("                                class=\"btn btn-primary\"\r\n");
      out.write("                                data-bs-toggle=\"modal\"\r\n");
      out.write("                                data-bs-target=\"#exampleModal\"\r\n");
      out.write("                                >\r\n");
      out.write("                                <i class=\"fa fa-car\" aria-hidden=\"true\"></i> Parquear\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th scope=\"col\">Propietario</th>\r\n");
      out.write("                                <th scope=\"col\">Placa Vehículo</th>\r\n");
      out.write("                                <th scope=\"col\">Plaza</th>\r\n");
      out.write("                                <th scope=\"col\">Fecha Ingreso</th>\r\n");
      out.write("                                <th scope=\"col\">Salida</th>\r\n");
      out.write("                                <th scope=\"col\">Borrar</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr ng-repeat=\"registro in regestado1\">\r\n");
      out.write("                                <td>{{ registro.nombre_propietario}}</td>\r\n");
      out.write("                                <td>{{ registro.placa_vehiculo}}</td>\r\n");
      out.write("                                <td>{{ registro.num_plaza}}</td>\r\n");
      out.write("                                <td>{{ registro.fecha_ingreso}}</td>\r\n");
      out.write("                                <td style=\"cursor: pointer\">\r\n");
      out.write("                                    <a\r\n");
      out.write("                                        class=\"btn btn-warning\"\r\n");
      out.write("                                        href=\"\"\r\n");
      out.write("                                        aria-label=\"Sign Out\"\r\n");
      out.write("                                        ng-click=\"actualizarRegistro(registro.id_registro_parqueo, registro.fecha_ingreso)\"\r\n");
      out.write("                                        >\r\n");
      out.write("                                        <i class=\"fa fa-sign-out\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td style=\"cursor: pointer\">\r\n");
      out.write("                                    <a\r\n");
      out.write("                                        class=\"btn btn-danger\"\r\n");
      out.write("                                        href=\"\"\r\n");
      out.write("                                        aria-label=\"Delete\"\r\n");
      out.write("                                        ng-click=\"borrarRegistro(registro.id_registro_parqueo)\"\r\n");
      out.write("                                        >\r\n");
      out.write("                                        <i class=\"fa fa-trash\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div\r\n");
      out.write("                    class=\"modal fade\"\r\n");
      out.write("                    id=\"exampleModal\"\r\n");
      out.write("                    tabindex=\"-1\"\r\n");
      out.write("                    aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("                    aria-hidden=\"true\"\r\n");
      out.write("                    >\r\n");
      out.write("                    <div class=\"modal-dialog\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("                            <div class=\"modal-header\">\r\n");
      out.write("                                <h5 class=\"modal-title\" id=\"exampleModalLabel\">\r\n");
      out.write("                                    REGISTRAR ENTRADA\r\n");
      out.write("                                </h5>\r\n");
      out.write("                                <button\r\n");
      out.write("                                    type=\"button\"\r\n");
      out.write("                                    class=\"btn-close\"\r\n");
      out.write("                                    data-bs-dismiss=\"modal\"\r\n");
      out.write("                                    aria-label=\"Close\"\r\n");
      out.write("                                    ></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"modal-body\">\r\n");
      out.write("                                <form>\r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <label class=\"form-label\" class=\"form-label\"\r\n");
      out.write("                                               >Nombre Propietario *</label\r\n");
      out.write("                                        >\r\n");
      out.write("                                        <input\r\n");
      out.write("                                            type=\"text\"\r\n");
      out.write("                                            required\r\n");
      out.write("                                            ng-model=\"nombre\"\r\n");
      out.write("                                            class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Nombre Propietario\"\r\n");
      out.write("                                            aria-describedby=\"nombrePropietario\"\r\n");
      out.write("                                            />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <label class=\"form-label\">Número Identificación *</label>\r\n");
      out.write("                                        <input\r\n");
      out.write("                                            type=\"text\"\r\n");
      out.write("                                            required\r\n");
      out.write("                                            ng-model=\"documento\"\r\n");
      out.write("                                            class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Número Identificación\"\r\n");
      out.write("                                            aria-describedby=\"nombrePropietario\"\r\n");
      out.write("                                            />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <label class=\"form-label\">Número Celular *</label>\r\n");
      out.write("                                        <input\r\n");
      out.write("                                            type=\"text\"\r\n");
      out.write("                                            required\r\n");
      out.write("                                            ng-model=\"celular\"\r\n");
      out.write("                                            class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Número Celular\"\r\n");
      out.write("                                            aria-describedby=\"nombrePropietario\"\r\n");
      out.write("                                            />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <label class=\"form-label\">Placa Vehículo *</label>\r\n");
      out.write("                                        <input\r\n");
      out.write("                                            type=\"text\"\r\n");
      out.write("                                            required\r\n");
      out.write("                                            ng-model=\"placa\"\r\n");
      out.write("                                            class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Placa vehículo\"\r\n");
      out.write("                                            aria-describedby=\"nombrePropietario\"\r\n");
      out.write("                                            />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <label class=\"form-label\">Plaza Aparcamiento *</label>\r\n");
      out.write("                                        <input\r\n");
      out.write("                                            type=\"text\"\r\n");
      out.write("                                            required\r\n");
      out.write("                                            ng-model=\"plaza\"\r\n");
      out.write("                                            class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Placa vehículo\"\r\n");
      out.write("                                            aria-describedby=\"nombrePropietario\"\r\n");
      out.write("                                            />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button\r\n");
      out.write("                                        type=\"submit\"\r\n");
      out.write("                                        class=\"btn btn-success\"\r\n");
      out.write("                                        ng-click=\"guardarRegistro()\"\r\n");
      out.write("                                        >\r\n");
      out.write("                                        Registrar\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <script src=\"controladorReg.js\"></script>\r\n");
      out.write("        </body>\r\n");
      out.write("    </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
